### PR TITLE
Fix linenumbers when using @q with macro calls

### LINKED ISSUE #107: @q doesn't work with macros
```julia
julia> @q @time(1+1)
:(#= REPL[5]:1 =# @time 1 + 1)
```

It could be fixed by postwalking and changing all the `:macrocall`s to have `nothing` for the line number, I believe?

### PR DESCRIPTION
**Pull request by cstjean**
Fix #107 by replacing the `:macrocall` line-number argument with `nothing`. I haven't read anywhere that this is Acceptable, but it seems to work.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Do you have a case where the current behaviour is a problem? I'm a bit wary of this given that macros are probably not expecting it in general.

**Comment by cstjean** [comment]
I `@macroexpand1` a macro call that expands into other macro calls, and the line numbers are an eyesore.

> I'm a bit wary of this given that macros are probably not expecting it in general.

Yeah, that's reasonable. We can leave the PR open until a more compelling use case comes up.

**Comment by Gnimuc** [comment]
I also hit this a while ago: https://stackoverflow.com/questions/53274001

It looks currently there is no elegant solution to strip line-number-node in `macrocall`s.

**Comment by cstjean** [comment]
FWIW, Jameson said on Slack that accepting `nothing` was intentional; “be liberal in what you accept, conservative in what you produce”.

**Pull request closed without merging**
