### PR TITLE
Support anonymous function in splitdef/combinedef

### LINKED ISSUE #93: Add splitdef for lambda functions
It would be useful for manipulating anonymous functions. Currently it shows:

```julia
julia> splitdef(:(x->x))
ERROR: AssertionError: Not a function definition: x->begin
        #= REPL[30]:1 =#
        x
    end
```

### PR DESCRIPTION
**Pull request by tkf**
These examples work now:

https://github.com/MikeInnes/MacroTools.jl/blob/8c003bc25d4298d2305d1ff20af2c0e9c2c013f0/test/split.jl#L58-L70

close #93

### CODE REVIEW

**Comment by tkf** [comment]
> if we shouldn't rewrite it as

It sounds like a great idea. I just tried to stick with the existing pattern.

**Comment by MasonProtter** [comment]
Perhaps MacroTools.jl should just use https://github.com/invenia/ExprTools.jl for splitdef and combinedef? ExprTools.jl's implementation is a bit more robust and performant from what I understand.

**Comment by cstjean** [comment]
That's #132

**Comment by MasonProtter** [comment]
:facepalm: oops, I should read more carefully.

**Comment by devmotion** [comment]
Is it possible to tag a release with these changes? I'd like to use this functionality and since I'm already using MacroTools it would be nice to avoid having to add ExprTools (which handles anonymous functions fine) as an additional dependency.

**Pull request merged**
