### PR TITLE
Fix most of 0.7 depwarns and test errors

### PR DESCRIPTION
**Pull request by yuyichao**
Just realized that this also includes https://github.com/MikeInnes/MacroTools.jl/pull/56

### CODE REVIEW

**Comment by yuyichao** [comment]
Ping.

**Comment by yuyichao** [comment]
Ping.

**Comment by yuyichao** [comment]
Ping???

**Comment by MikeInnes** [comment]
:+1:

**Comment by cstjean** [comment]
Could we please get a release?

**Pull request merged**
