### PR TITLE
don't print nothing

### PR DESCRIPTION
**Pull request by oxinabox**
not until
https://github.com/JuliaLang/julia/pull/32148

### CODE REVIEW

**Comment by MikeInnes** [comment]
How about changing the original code to use `repr(fdef)`. Seems like that'd be more correct in general anyway (e.g. for strings).

**Comment by oxinabox** [comment]
🤷‍♂  could do.
`repr` can be super verbose though.

**Comment by oxinabox** [comment]
Do you still want it changed to repr?

**Comment by MikeInnes** [comment]
In what cases is `repr` much more verbose? It seems like it'd be fine for Exprs, if so then yeah I think best to change it.

**Comment by oxinabox** [comment]
Yeah it is find for Exprs, so fair

**Comment by MikeInnes** [comment]
:+1:

**Pull request merged**
